# Generated by Django 5.0.1 on 2026-01-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('standard', 'Personal Project'), ('freelance', 'Freelance Project')], default='standard', max_length=20),
        ),
    ]
