# Generated by Django 5.0.1 on 2026-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('api_security', 'API Security'), ('data_protection', 'Data Protection'), ('infrastructure', 'Infrastructure Security'), ('compliance', 'Compliance & Standards')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the security feature')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Security Feature',
                'verbose_name_plural': 'Security Features',
                'ordering': ['order', 'category', 'title'],
            },
        ),
    ]
