# Generated by Django 5.0.1 on 2026-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Professional role/title', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('summary', models.TextField(help_text='Professional summary/bio')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one profile should be active')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
