# Generated by Django 5.0.1 on 2026-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g., Master of Computer Applications', max_length=200)),
                ('field', models.CharField(help_text='Field of study', max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='CGPA obtained', max_digits=4)),
                ('max_cgpa', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum CGPA', max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = most recent)')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
